name: Book Project CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy FastAPI App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your-ec2-public-ip >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@"${{secrets.EC2_PUBLIC_IP}}" << 'EOF'
            cd fastapi-book-project

            # Pull latest changes
            git pull origin main

            # Rebuild and restart the Docker container
            sudo docker-compose down
            sudo docker-compose up -d --build

            # Restart Nginx
            sudo systemctl restart nginx
          EOF